description: Execution environment with gen-circleci-orb pre-installed.
docker:
- image: jerusdp/gen-circleci-orb:<< parameters.tag >>
parameters:
  tag:
    type: string
    description: Docker image tag.
    default: latest
