set -- gen-circleci-orb init
set -- "$@" --binary "${BINARY}"
[[ -n "${PUBLIC_ORB_NAMESPACE:-}" ]] && set -- "$@" --public-orb-namespace "${PUBLIC_ORB_NAMESPACE}"
[[ -n "${PRIVATE_ORB_NAMESPACE:-}" ]] && set -- "$@" --private-orb-namespace "${PRIVATE_ORB_NAMESPACE}"
set -- "$@" --build-workflow "${BUILD_WORKFLOW}"
set -- "$@" --release-workflow "${RELEASE_WORKFLOW}"
[[ -n "${REQUIRES_JOB:-}" ]] && set -- "$@" --requires-job "${REQUIRES_JOB}"
set -- "$@" --crate-tag-prefix "${CRATE_TAG_PREFIX}"
set -- "$@" --release-after-job "${RELEASE_AFTER_JOB}"
[[ -n "${ORB_DIR:-}" ]] && set -- "$@" --orb-dir "${ORB_DIR}"
[[ -n "${CI_DIR:-}" ]] && set -- "$@" --ci-dir "${CI_DIR}"
[[ -n "${ORB_TOOLS_VERSION:-}" ]] && set -- "$@" --orb-tools-version "${ORB_TOOLS_VERSION}"
[[ -n "${DOCKER_ORB_VERSION:-}" ]] && set -- "$@" --docker-orb-version "${DOCKER_ORB_VERSION}"
set -- "$@" --docker-namespace "${DOCKER_NAMESPACE}"
[[ -n "${DOCKER_CONTEXT:-}" ]] && set -- "$@" --docker-context "${DOCKER_CONTEXT}"
[[ -n "${ORB_CONTEXT:-}" ]] && set -- "$@" --orb-context "${ORB_CONTEXT}"
[[ -n "${GEN_CIRCLECI_ORB_VERSION:-}" ]] && set -- "$@" --gen-circleci-orb-version "${GEN_CIRCLECI_ORB_VERSION}"
[[ "${MCP:-false}" = "true" ]] && set -- "$@" --mcp
[[ -n "${MCP_EARLIEST_VERSION:-}" ]] && set -- "$@" --mcp-earliest-version "${MCP_EARLIEST_VERSION}"
[[ -n "${MCP_CONTEXT:-}" ]] && set -- "$@" --mcp-context "${MCP_CONTEXT}"
[[ -n "${GIT_PUSH_SUBCOMMANDS:-}" ]] && set -- "$@" --git-push-subcommands "${GIT_PUSH_SUBCOMMANDS}"
[[ -n "${HOME_URL:-}" ]] && set -- "$@" --home-url "${HOME_URL}"
[[ -n "${SOURCE_URL:-}" ]] && set -- "$@" --source-url "${SOURCE_URL}"
[[ "${RECORD:-false}" = "true" ]] && set -- "$@" --record
[[ -n "${RECORD_GPG_KEY_ENV:-}" ]] && set -- "$@" --record-gpg-key-env "${RECORD_GPG_KEY_ENV}"
[[ -n "${RECORD_GPG_TRUST_ENV:-}" ]] && set -- "$@" --record-gpg-trust-env "${RECORD_GPG_TRUST_ENV}"
[[ -n "${RECORD_USER_NAME_ENV:-}" ]] && set -- "$@" --record-user-name-env "${RECORD_USER_NAME_ENV}"
[[ -n "${RECORD_USER_EMAIL_ENV:-}" ]] && set -- "$@" --record-user-email-env "${RECORD_USER_EMAIL_ENV}"
[[ -n "${RECORD_SIGNING_KEY_ENV:-}" ]] && set -- "$@" --record-signing-key-env "${RECORD_SIGNING_KEY_ENV}"
[[ -n "${RECORD_PUSH_SSH_FINGERPRINT:-}" ]] && set -- "$@" --record-push-ssh-fingerprint "${RECORD_PUSH_SSH_FINGERPRINT}"
[[ -n "${RECORD_CONTEXT:-}" ]] && set -- "$@" --record-context "${RECORD_CONTEXT}"
[[ "${DRY_RUN:-false}" = "true" ]] && set -- "$@" --dry-run
"$@"
